### ISSUE TITLE
No reference to github on docs.folktalejs.org

### ISSUE THREAD

**Issue by Izhaki** [folktale/folktale.github.io#11]
Having landed on the docs site, was a bit annoying not finding any link back to github to report an issue. I actually had to go on google and search for this repository.

Would be nice to add a reference to github on the docs section.

**Comment by robotlolita** [comment]
Ah. This is also a problem in the new docs (at http://origamitower.github.io/folktale/api/en/folktale.html). Could you open an issue here https://github.com/origamitower/folktale/issues?
